//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_alert_pattern_H
#define METASPRITE_alert_pattern_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define alert_pattern_TILE_ORIGIN 0
#define alert_pattern_TILE_H 8
#define alert_pattern_WIDTH 160
#define alert_pattern_HEIGHT 144
#define alert_pattern_TILE_COUNT 32
#define alert_pattern_MAP_ATTRIBUTES alert_pattern_map_attributes
#define alert_pattern_TILE_PALS 0

BANKREF_EXTERN(alert_pattern)

extern const palette_color_t alert_pattern_palettes[4];
extern const uint8_t alert_pattern_tiles[512];

extern const unsigned char alert_pattern_map[360];
extern const unsigned char alert_pattern_map_attributes[360];

#endif