// This file was generated by img2gb, DO NOT EDIT

#ifndef _BUTTON_TILES_H
#define _BUTTON_TILES_H

#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF_EXTERN(BUTTONS)

extern const UINT8 BUTTONS[];
#define BUTTONS_TILE_COUNT 64


#endif
