// This file was generated by img2gb, DO NOT EDIT

#ifndef _BUTTON_ARROW_H
#define _BUTTON_ARROW_H

#include <gb/gb.h>
#include <gbdk/platform.h>
BANKREF_EXTERN(BUTTON_ARROW)
extern const UINT8 BUTTON_ARROW[];
#define BUTTON_ARROW_TILE_COUNT 64


#endif
