//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_checkerboard_32x32_H
#define METASPRITE_checkerboard_32x32_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define checkerboard_32x32_TILE_ORIGIN 0
#define checkerboard_32x32_TILE_H 8
#define checkerboard_32x32_WIDTH 160
#define checkerboard_32x32_HEIGHT 144
#define checkerboard_32x32_TILE_COUNT 2
#define checkerboard_32x32_MAP_ATTRIBUTES checkerboard_32x32_map_attributes
#define checkerboard_32x32_TILE_PALS 0

BANKREF_EXTERN(checkerboard_32x32_palettes)
extern const palette_color_t checkerboard_32x32_palettes[4];
BANKREF_EXTERN(checkerboard_32x32_tiles)
extern const uint8_t checkerboard_32x32_tiles[32];

BANKREF_EXTERN(checkerboard_32x32_map)
extern const unsigned char checkerboard_32x32_map[360];
BANKREF_EXTERN(checkerboard_32x32_map_attributes)
extern const unsigned char checkerboard_32x32_map_attributes[360];

#endif