/*

 COLORBARS_LEFTRIGHT.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : X:\gbc_hacks\gbdk\examples\gb\fischsdiags_v2\res\bar_c.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#ifndef __colorbars_leftright_h_INCLUDE
#define __colorbars_leftright_h_INCLUDE

#include <gb/gb.h>
#include <gbdk/platform.h>

#define ColorbarsLeftToRightWidth 20
#define ColorbarsLeftToRightHeight 18
#define ColorbarsLeftToRightBank 0

BANKREF_EXTERN(ColorbarsLeftToRight)
extern const unsigned char ColorbarsLeftToRight[];

#endif

/* End of COLORBARS_LEFTRIGHT.H */
