/*

 COLORBARS_RIGHTLEFT.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : X:\gbc_hacks\gbdk\examples\gb\fischsdiags_v2\res\bar_c.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#ifndef __colorbars_rightleft_h_INCLUDE
#define __colorbars_rightleft_h_INCLUDE

#include <gb/gb.h>
#include <gbdk/platform.h>

#define ColorbarsRightToLeftWidth 20
#define ColorbarsRightToLeftHeight 18
#define ColorbarsRightToLeftBank 0

BANKREF_EXTERN(ColorbarsRightToLeft)
extern const unsigned char ColorbarsRightToLeft[];

#endif

/* End of COLORBARS_RIGHTLEFT.H */
