//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>
/*
BANKREF(menu_arrow_palettes)
const palette_color_t menu_arrow_palettes[4] = {
	RGB8(255, 255, 255), RGB8(0, 0, 0), RGB8(80, 1, 7), RGB8(254, 1, 0)
};
*/
BANKREF(menu_arrow_tiles)
const uint8_t menu_arrow_tiles[16] = {
	0x10,0x00,0x30,0x00,0x70,0x00,0xff,0x00,0xff,0x00,0x70,0x00,0x30,0x00,0x10,0x00
};

/*
BANKREF(menu_arrow_metasprite0)
const metasprite_t menu_arrow_metasprite0[] = {
	METASPR_ITEM(-4, -4, 0, 0), METASPR_TERM
};

BANKREF(menu_arrow_metasprites)
const metasprite_t* const menu_arrow_metasprites[1] = {
	menu_arrow_metasprite0
};
*/