//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_passfail_bg_H
#define METASPRITE_passfail_bg_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define passfail_bg_TILE_ORIGIN 0
#define passfail_bg_TILE_H 8
#define passfail_bg_WIDTH 160
#define passfail_bg_HEIGHT 144
#define passfail_bg_TILE_COUNT 114
#define passfail_bg_MAP_ATTRIBUTES passfail_bg_map_attributes
#define passfail_bg_TILE_PALS 0

BANKREF_EXTERN(passfail_bg)

extern const palette_color_t passfail_bg_palettes[4];
extern const uint8_t passfail_bg_tiles[1824];

extern const unsigned char passfail_bg_map[360];
extern const unsigned char passfail_bg_map_attributes[360];

#endif