//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_menu_background_H
#define METASPRITE_menu_background_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define menu_background_TILE_ORIGIN 0
#define menu_background_TILE_H 8
#define menu_background_WIDTH 160
#define menu_background_HEIGHT 144
#define menu_background_TILE_COUNT 123
#define menu_background_MAP_ATTRIBUTES menu_background_map_attributes
#define menu_background_TILE_PALS 0

BANKREF_EXTERN(menu_background)

extern const palette_color_t menu_background_palettes[4];
extern const uint8_t menu_background_tiles[1968];

extern const unsigned char menu_background_map[360];
extern const unsigned char menu_background_map_attributes[360];

#endif