//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_gblink_bg_H
#define METASPRITE_gblink_bg_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define gblink_bg_TILE_ORIGIN 0
#define gblink_bg_TILE_H 8
#define gblink_bg_WIDTH 160
#define gblink_bg_HEIGHT 144
#define gblink_bg_TILE_COUNT 82
#define gblink_bg_MAP_ATTRIBUTES gblink_bg_map_attributes
#define gblink_bg_TILE_PALS 0

BANKREF_EXTERN(gblink_bg)

extern const palette_color_t gblink_bg_palettes[8];
extern const uint8_t gblink_bg_tiles[1312];

extern const unsigned char gblink_bg_map[360];
extern const unsigned char gblink_bg_map_attributes[360];

#endif