#pragma bank 1
//AUTOGENERATED FILE FROM png2asset
#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(menu_arrow_palettes)
const palette_color_t menu_arrow_palettes[4] = {
	RGB8(255, 0, 0), RGB8(0, 0, 0), RGB8(80, 1, 7), RGB8(254, 1, 0)
};

BANKREF(menu_arrow_tiles)
const uint8_t menu_arrow_tiles[16] = {
	0x10,0x00,0x30,0x00,0x70,0x00,0xff,0x00,0xff,0x00,0x70,0x00,0x30,0x00,0x10,0x00
};

BANKREF(menu_arrow_display)
void menu_arrow_display() BANKED
{
    SPRITES_8x8;
    set_sprite_palette(0, 1, menu_arrow_palettes);
    set_sprite_data(0, 8, menu_arrow_tiles);
    set_sprite_tile(0, 0);
    SHOW_SPRITES;
}