//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_menu_arrow_H
#define METASPRITE_menu_arrow_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define menu_arrow_TILE_ORIGIN 0
#define menu_arrow_TILE_H 8
#define menu_arrow_WIDTH 8
#define menu_arrow_HEIGHT 8
#define menu_arrow_TILE_COUNT 1
#define menu_arrow_PIVOT_X 4
#define menu_arrow_PIVOT_Y 4
#define menu_arrow_PIVOT_W 8
#define menu_arrow_PIVOT_H 8

BANKREF_EXTERN(menu_arrow_palettes)
extern const palette_color_t menu_arrow_palettes[4];
BANKREF_EXTERN(menu_arrow_tiles)
extern const uint8_t menu_arrow_tiles[16];

BANKREF_EXTERN(menu_arrow_display)
extern void menu_arrow_display() BANKED;

#endif