//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_scroll_pattern_H
#define METASPRITE_scroll_pattern_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define scroll_pattern_TILE_ORIGIN 0
#define scroll_pattern_TILE_H 8
#define scroll_pattern_WIDTH 160
#define scroll_pattern_HEIGHT 144
#define scroll_pattern_TILE_COUNT 3
#define scroll_pattern_MAP_ATTRIBUTES scroll_pattern_map_attributes
#define scroll_pattern_TILE_PALS 0

BANKREF_EXTERN(scroll_pattern)

extern const palette_color_t scroll_pattern_palettes[4];
extern const uint8_t scroll_pattern_tiles[48];

extern const unsigned char scroll_pattern_map[360];
extern const unsigned char scroll_pattern_map_attributes[360];

#endif